name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy code
        run: |
          rsync -avz --exclude='.git*' --exclude='*.pyc' ./ rohit@192.168.187.50:/var/www/html/
          sshpass -p "rohit" ssh rohit@192.168.187.50 "sudo systemctl restart apache2"
